apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: otus-sa-01-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /otusapp/anfilat($|/)(.*)
            backend:
              serviceName: otus-sa-01-service
              servicePort: 8000
